services:
  ex-esdb-gater:
    image: local/ex-esdb-gater
    build:
      context: ../system
    hostname: gater00
    container_name: ex-esdb-gater
    profiles:
      - gater
    networks:
      - ex-esdb-net
    environment:
      RELEASE_COOKIE: ${EX_ESDB_COOKIE}
      EX_ESDB_COOKIE: ${EX_ESDB_COOKIE}
      EX_ESDB_CLUSTER_SECRET: ${EX_ESDB_CLUSTER_SECRET}
    stop_grace_period: 10s

networks:
  ex-esdb-net:
    external: true
    name: ex-esdb-net
